---
- hosts: all
  gather_facts: yes

  tasks:
    - name: "Populate service facts"
      service_facts:
    - name: "Check if HTTPD if running."
      debug:
        msg: "{{ansible_facts.services['httpd.service'].state}}"
   