---
- hosts: all
  gather_facts: yes

  tasks:
    - name: "Check top 10 cpu"
      ansible.builtin.shell:
        cmd: ps aux --sort -%cpu | head -n 10
      register: top_cpu

    - name: Display top 10 CPU usage
      debug:
        msg: "{{ top_cpu.stdout_lines }}"
   