---
- hosts: all
  gather_facts: yes

  

  tasks:
    - name: "Check Running processes using top"
      ansible.builtin.shell:
        cmd: ps aux --sort -%mem | head -n 10
      register: memory

    - name: Display top 10 memory
      debug:
        msg: "{{ memory.stdout_lines }}"
   