---
- hosts: all
  gather_facts: yes

  tasks:
    - name: "Check Running processes using top"
      ansible.builtin.shell:
        cmd: ps aux --sort -%cpu | head -n 10
      register: cpu

    - debug:
        var: cpu
   