---
- hosts: all
  gather_facts: no
  tasks:
    - name: Test connectivity to Linux host
      ping:
      when: ansible_os_family == "Linux"

    - name: Test connectivity to Windows host
      win_ping:
      when: ansible_os_family == "Windows"
